"""ChatMessageCreate

Revision ID: 01e3c35dbfdd
Revises: 5bba9ddd0402
Create Date: 2024-11-26 16:59:31.977256

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '01e3c35dbfdd'
down_revision = '5bba9ddd0402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
