"""chat model fix

Revision ID: 26747dd59866
Revises: fffa2f0fef37
Create Date: 2024-11-26 18:49:53.423118

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '26747dd59866'
down_revision = 'fffa2f0fef37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
