"""fix field

Revision ID: 5bba9ddd0402
Revises: dcb7b6e38001
Create Date: 2024-11-26 06:54:34.795903

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5bba9ddd0402'
down_revision = 'dcb7b6e38001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
