"""chat model fix

Revision ID: 80d7eaf30d5b
Revises: 26747dd59866
Create Date: 2024-11-26 18:53:45.355894

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '80d7eaf30d5b'
down_revision = '26747dd59866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
