"""chat model fix

Revision ID: 837acdef5ff5
Revises: 80d7eaf30d5b
Create Date: 2024-11-26 19:02:59.394815

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '837acdef5ff5'
down_revision = '80d7eaf30d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
