"""Initial migration

Revision ID: 9a6ce3665e4b
Revises: af8fd03009d3
Create Date: 2024-11-25 10:13:15.044922

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9a6ce3665e4b'
down_revision = 'af8fd03009d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
