"""Initial migration

Revision ID: af8fd03009d3
Revises: e0df99773ec3
Create Date: 2024-11-25 10:06:38.409153

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'af8fd03009d3'
down_revision = 'e0df99773ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
